name: Daily Turo Scrape

on:
  schedule:
    - cron: '0 3 * * *' # Runs at 3:00 AM every day
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Scraper
        run: python scraper.py

      - name: SFTP Deploy to Domain.com
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 2222
          source: "turo_data.json"
          target: "./public_html/turo-app/"
