name: Daily Turo Scrape

on:
  schedule:
    - cron: '0 3 * * *' # Runs at 3:00 AM every day
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Scraper
        run: python scraper.py

      - name: Native SFTP Upload
        run: |
          sudo apt-get install -y sshpass
          export SSHPASS="${{ secrets.FTP_PASSWORD }}"
          sshpass -e sftp -o StrictHostKeyChecking=no -P 2222 ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }} <<EOF
          put turo_data.json public_html/turo-app/turo_data.json
          bye
          EOF
